#
# ObjectWindows - (C) Copyright 1991 by Borland International
#

# Do not build this program in small or medium model.
MODEL = l

!include "..\makefile.inc"

checkers.exe: turboc.cfg checkers.obj board.obj info.obj checkers.res
     $(TLINK) $(LFLAGS) $(BCLIBDIR)\c0w$(MODEL) checkers board info,checkers,,@&&!
$(OWLROOT)\lib\bwcc.lib $(OWLLIBS) $(STDLIBS)
!,$(OWLROOT)\lib\owl.def
     rc -K checkers.res checkers.exe

checkers.res : checkers.rc blackkng.bmp blackman.bmp redking.bmp redman.bmp \
     checkers.ico hand.cur handpc.cur checkers.h

turboc.cfg: makefile ..\makefile.inc
	echo -I$(INCLUDE) >turboc.cfg

clean:
	del *.obj
	del *.exe
	del *.res
	del *.dll
	del *.lib
	del *.map
	del *.sym
