#
# ObjectWindows - (C) Copyright 1991 by Borland International
#

!include "..\makefile.inc"

calc.exe: turboc.cfg calc.obj calc.res
     $(TLINK)  $(LFLAGS) $(BCLIBDIR)\c0w$(MODEL) calc,calc,,@&&!
$(OWLLIBS) $(STDLIBS)
!,$(OWLROOT)\lib\owl.def
     rc -K calc.res calc.exe

turboc.cfg: makefile ..\makefile.inc
	echo -I$(INCLUDE) >turboc.cfg

clean:
	del *.obj
	del *.exe
	del *.res
	del *.dll
	del *.lib
	del *.map
	del *.sym
