#
# ObjectWindows - (C) Copyright 1991 by Borland International
#

!include "..\makefile.inc"

gdidemo.exe: turboc.cfg gdidemo.obj arty.obj bitblt.obj font.obj line.obj gdidemo.res
     $(TLINK) $(LFLAGS) $(BCLIBDIR)\c0w$(MODEL) gdidemo arty bitblt font line,@&&!
gdidemo

$(OWLLIBS) $(STDLIBS)
!,$(OWLROOT)\lib\owl.def
     rc -K gdidemo.res gdidemo.exe

gdidemo.res : gdidemo.rc backgrnd.bmp ship.bmp monoship.bmp

turboc.cfg: makefile ..\makefile.inc
	echo -I$(INCLUDE) >turboc.cfg

clean:
	del *.obj
	del *.exe
	del *.res
	del *.dll
	del *.lib
	del *.map
	del *.sym
