#
# ObjectWindows - (C) Copyright 1991 by Borland International
#

!include "..\makefile.inc"

progtalk.exe: turboc.cfg progtalk.obj ddeclien.obj progtalk.res
     $(TLINK) $(LFLAGS) $(BCLIBDIR)\c0w$(MODEL) progtalk ddeclien,progtalk,,@&&!
$(OWLLIBS) $(STDLIBS)
!,$(OWLROOT)\lib\owl.def
     rc -K progtalk.res progtalk.exe

turboc.cfg: makefile ..\makefile.inc
	echo -I$(INCLUDE) >turboc.cfg

clean:
	del *.obj
	del *.exe
	del *.res
	del *.dll
	del *.lib
	del *.map
	del *.sym
