#
# ObjectWindows - (C) Copyright 1991 by Borland International
#

!include "..\makefile.inc"

fileapp.exe: turboc.cfg fileapp.obj fileapp.res
     $(TLINK) $(LFLAGS) $(BCLIBDIR)\c0w$(MODEL) fileapp,fileapp,,@&&!
$(OWLLIBS) $(STDLIBS)
!,$(OWLROOT)\lib\owl.def
     rc -K fileapp.res fileapp.exe

turboc.cfg: makefile ..\makefile.inc
	echo -I$(INCLUDE) >turboc.cfg

clean:
	del *.obj
	del *.exe
	del *.res
	del *.dll
	del *.lib
	del *.map
	del *.sym
